### ISSUE TITLE
Live monitor report - You can not see the page with anonymous user

### ISSUE THREAD

**Issue by mldk-tech** [Gizra/imanimo-shoov#3]
![imanimo](https://cloud.githubusercontent.com/assets/5812423/12535397/7f2f2b7e-c28a-11e5-96d9-a817874ccb9f.png)

**Comment by bricel** [comment]
@DavidKohav - Yes this is on purpose, you can change the test to this page http://www.imanimo.com/sienna-dress#/Blue

**Comment by mldk-tech** [comment]
Done
